[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","B","UP"]
ignore = ["E501"]

[tool.mypy]
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
pretty = true

# Keep testing options in pytest.ini as requested
