version: "3.9"
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -lc "python -V && sleep infinity"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: {}
