app = "aelis"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 40

  [http_service.checks.health]
    grace_period = "10s"
    interval = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"

[metrics]
  port = 8080
  path = "/metrics"
