name: Release – GHCR & SBOM on tag

on:
  push:
    tags:
      - 'Snapshot-OK-*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  release:
    name: Build & Push Image + SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercased repo owner/name
        id: repo
        run: |
          owner="${{ github.repository_owner }}"
          repo="${{ github.event.repository.name }}"
          echo "owner_lc=${owner,,}" >> $GITHUB_OUTPUT
          echo "name_lc=${repo,,}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.owner_lc }}/${{ steps.repo.outputs.name_lc }}:${{ github.ref_name }}
            ghcr.io/${{ steps.repo.outputs.owner_lc }}/${{ steps.repo.outputs.name_lc }}:latest

      - name: Generate SBOM (CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          artifact-name: "sbom-cyclonedx"
          upload-artifact: true
          format: cyclonedx-json

      - name: Summary
        run: |
          echo "Pushed: ghcr.io/${{ steps.repo.outputs.owner_lc }}/${{ steps.repo.outputs.name_lc }}:${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
