"""create radar_entries

Revision ID: 1bd3051d66f6
Revises: edb89f59f02c
Create Date: 2026-02-26 07:26:36.139219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bd3051d66f6"
down_revision: Union[str, Sequence[str], None] = "edb89f59f02c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "radar_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("dpi_code", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("days_to_expiry", sa.Integer(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_radar_entries_tenant_expiry", "radar_entries", ["tenant", "expiry_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_radar_entries_tenant_expiry", table_name="radar_entries")
    op.drop_table("radar_entries")
    # ### end Alembic commands ###
