"""radar_entries

Revision ID: edb89f59f02c
Revises: fbb982703e72
Create Date: 2026-02-26 07:04:34.831855

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "edb89f59f02c"
down_revision: Union[str, Sequence[str], None] = "fbb982703e72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
