"""radar_entries table only (20260225_190209)

Revision ID: fbb982703e72
Revises: 14252af2016e
Create Date: 2026-02-25 19:02:10.356368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbb982703e72"
down_revision: Union[str, Sequence[str], None] = "14252af2016e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orchestrator_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=False),
        sa.Column("ref_id", sa.String(length=64), nullable=False),
        sa.Column("threshold_days", sa.Integer(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant",
            "ref_type",
            "ref_id",
            "threshold_days",
            "event_date",
            name="uq_orchestrator_event",
        ),
    )
    op.create_index(
        "ix_orch_ref", "orchestrator_events", ["tenant", "ref_type", "ref_id"], unique=False
    )
    op.create_index(
        "ix_orch_tenant_status_date",
        "orchestrator_events",
        ["tenant", "status", "event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orchestrator_events_event_date"),
        "orchestrator_events",
        ["event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orchestrator_events_ref_id"), "orchestrator_events", ["ref_id"], unique=False
    )
    op.create_index(
        op.f("ix_orchestrator_events_ref_type"), "orchestrator_events", ["ref_type"], unique=False
    )
    op.create_index(
        op.f("ix_orchestrator_events_status"), "orchestrator_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_orchestrator_events_tenant"), "orchestrator_events", ["tenant"], unique=False
    )
    op.create_table(
        "orchestrator_locks",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("token", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index("ix_orch_lock_until", "orchestrator_locks", ["locked_until"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orch_lock_until", table_name="orchestrator_locks")
    op.drop_table("orchestrator_locks")
    op.drop_index(op.f("ix_orchestrator_events_tenant"), table_name="orchestrator_events")
    op.drop_index(op.f("ix_orchestrator_events_status"), table_name="orchestrator_events")
    op.drop_index(op.f("ix_orchestrator_events_ref_type"), table_name="orchestrator_events")
    op.drop_index(op.f("ix_orchestrator_events_ref_id"), table_name="orchestrator_events")
    op.drop_index(op.f("ix_orchestrator_events_event_date"), table_name="orchestrator_events")
    op.drop_index("ix_orch_tenant_status_date", table_name="orchestrator_events")
    op.drop_index("ix_orch_ref", table_name="orchestrator_events")
    op.drop_table("orchestrator_events")
    # ### end Alembic commands ###
