"""init_cataloghi

Revision ID: 202511010133
Revises:
Create Date: 2025-11-01 01:33:50.465040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "202511010133"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogo_ancoraggi",
        sa.Column("codice", sa.String(length=32), nullable=False),
        sa.Column("descrizione", sa.String(length=255), nullable=True),
        sa.Column("categoria", sa.String(length=64), nullable=True),
        sa.Column("prezzo_eur", sa.Float(), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("codice"),
    )
    op.create_table(
        "catalogo_dpi",
        sa.Column("codice", sa.String(length=32), nullable=False),
        sa.Column("descrizione", sa.String(length=255), nullable=True),
        sa.Column("categoria", sa.String(length=64), nullable=True),
        sa.Column("prezzo_eur", sa.Float(), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("codice"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalogo_dpi")
    op.drop_table("catalogo_ancoraggi")
    # ### end Alembic commands ###
