name: Dependabot auto-merge
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v7
        if: steps.meta.outputs.update-type == 'version-update:semver-patch'
        with:
          script: |
            const pr = context.payload.pull_request.number;
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: pr,
              merge_method: "squash"
            });
